### ISSUE TITLE
Takes forever to plan a path

### ISSUE THREAD

**Issue by HernandoR** [theresejoseph/Trajectory_Tracking_via_MCAN#1]
Dear all

I'm trying to reperform the code of `TestEnvironmentPathPlanning`

Specifically, in the loop of 
```
        try:
            dx = DistanceTransformPlanner(
                img, goal=locations[i + 1], distance="euclidean"
            )
            dx.plan()
            path = dx.query(start=locations[i])
        except TimeoutError:
            # locations.append(free_spaces, k=1)
            print("removed a goal")
            continue
        paths.append(path)
        print(f"done {i+1} paths")
```

It seems taking forever on the line:
```
dx.plan()
```

I made some digs on the source code of robotic toolbox but didn't find where to set a `Timeout time` or to raise a TimeoutError.

Is this generally the case? How much time should I expect?

Regards

**Comment by HernandoR** [comment]
7~8 mins / it

**Comment by theresejoseph** [comment]
The distance transform planner can take a long time to solve depending on the size of the map and the distance between the two randomly generated locations. I've modified the code now to remove paths that take longer than 60 seconds to solve. This can be modified based on preference.
